"""Add provider chooser to patient form

Revision ID: 04d2353f942d
Revises: 9a80efbe6ba9
Create Date: 2020-06-11 13:20:25.864292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d2353f942d'
down_revision = '9a80efbe6ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_provider', 'provider', ['patient_provider_id'], ['id'])

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_facility', 'facility', ['provider_facility_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_provider_id')

    # ### end Alembic commands ###
