"""Adding facility and facility-category tables

Revision ID: 45a31f5c1409
Revises: 51241a47deae
Create Date: 2020-06-10 11:48:58.031971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a31f5c1409'
down_revision = '51241a47deae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_name', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_category_code_name'), 'facility_category', ['code_name'], unique=False)
    op.create_index(op.f('ix_facility_category_name'), 'facility_category', ['name'], unique=False)
    op.execute("INSERT INTO facility_category VALUES (1, 'NONE', '')")
    op.execute("INSERT INTO facility_category VALUES (2, 'HOSP', 'Hospital')")
    op.execute("INSERT INTO facility_category VALUES (3, 'CARDCL', 'Cardiology Clinic')")
    op.execute("INSERT INTO facility_category VALUES (4, 'GENCL', 'General Outpatient Clinic')")
    op.execute("INSERT INTO facility_category VALUES (5, 'SPECCL', 'Specialty Outpatient Clinic')")
    op.execute("INSERT INTO facility_category VALUES (6, 'SURGCTR', 'Cardiac Surgical/Cath Center')")
    op.execute("INSERT INTO facility_category VALUES (7, 'OTHER', 'Other Facility Type')")
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=30), nullable=False),
    sa.Column('facility_id', sa.String(length=10), nullable=True),
    sa.Column('facility_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_category_id'], ['facility_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_facility_id'), 'facility', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_facility_name'), 'facility', ['facility_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_facility_name'), table_name='facility')
    op.drop_index(op.f('ix_facility_facility_id'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_facility_category_name'), table_name='facility_category')
    op.drop_index(op.f('ix_facility_category_code_name'), table_name='facility_category')
    op.drop_table('facility_category')
    # ### end Alembic commands ###
