"""Provider and provider-category table creation

Revision ID: 51241a47deae
Revises: 21b21048b3fe
Create Date: 2020-06-10 10:54:26.944262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51241a47deae'
down_revision = '21b21048b3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_name', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_category_code_name'), 'provider_category', ['code_name'], unique=False)
    op.create_index(op.f('ix_provider_category_name'), 'provider_category', ['name'], unique=False)
    op.execute("INSERT INTO provider_category VALUES (1, 'NONE', '')")
    op.execute("INSERT INTO provider_category VALUES (2, 'CARD', 'Cardiologist')")
    op.execute("INSERT INTO provider_category VALUES (3, 'MD', 'MD')")
    op.execute("INSERT INTO provider_category VALUES (4, 'NURSE', 'Nurse')")
    op.execute("INSERT INTO provider_category VALUES (5, 'SOCW', 'Social Worker')")
    op.execute("INSERT INTO provider_category VALUES (6, 'SURG', 'Surgeon')")
    op.execute("INSERT INTO provider_category VALUES (7, 'OCLIN', 'Other (Clinical)')")
    op.execute("INSERT INTO provider_category VALUES (8, 'ONOTC', 'Other (Non-Clinical)')")
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('provider_id', sa.String(length=10), nullable=True),
    sa.Column('provider_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_category_id'], ['provider_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_first_name'), 'provider', ['first_name'], unique=False)
    op.create_index(op.f('ix_provider_last_name'), 'provider', ['last_name'], unique=False)
    op.create_index(op.f('ix_provider_provider_id'), 'provider', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_provider_id'), table_name='provider')
    op.drop_index(op.f('ix_provider_last_name'), table_name='provider')
    op.drop_index(op.f('ix_provider_first_name'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_provider_category_name'), table_name='provider_category')
    op.drop_index(op.f('ix_provider_category_code_name'), table_name='provider_category')
    op.drop_table('provider_category')
    # ### end Alembic commands ###
