"""empty message

Revision ID: 21b21048b3fe
Revises: c3bf2b366728
Create Date: 2020-06-09 13:39:21.891796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b21048b3fe'
down_revision = 'c3bf2b366728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('patient_id', sa.String(length=10)))
    op.create_index(op.f('ix_patient_patient_id'), 'patient', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_patient_id'), table_name='patient')
    op.drop_column('patient', 'patient_id')
    # ### end Alembic commands ###
