"""Adding test tables for dynamic fields

Revision ID: 52ba9c3b0a3a
Revises: 63f29fa3a90e
Create Date: 2020-06-24 10:31:37.733225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ba9c3b0a3a'
down_revision = '63f29fa3a90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pp_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pp_set_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pp_set_id'], ['pp_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('duo')
    op.drop_table('pp_set')
    # ### end Alembic commands ###
