"""Add gender and dob to patient form

Revision ID: 63f29fa3a90e
Revises: 04d2353f942d
Create Date: 2020-06-18 13:10:02.650619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f29fa3a90e'
down_revision = '04d2353f942d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_dob', sa.Date()))
        batch_op.add_column(sa.Column('patient_dob_est', sa.Boolean()))
        batch_op.add_column(sa.Column('patient_gender', sa.String()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('patient_gender')
        batch_op.drop_column('patient_dob_est')
        batch_op.drop_column('patient_dob')

    # ### end Alembic commands ###
