"""Add diagnosis field

Revision ID: 890b136e6a13
Revises: 63f29fa3a90e
Create Date: 2020-07-15 12:06:28.426603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890b136e6a13'
down_revision = '63f29fa3a90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icd_code', sa.String(length=10), nullable=True),
    sa.Column('icd_subcode', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('dx_abbrev', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_diagnosis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_diagnosis_dx_abbrev'), ['dx_abbrev'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_diagnosis_icd_code'), ['icd_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_diagnosis_icd_subcode'), ['icd_subcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_diagnosis_name'), ['name'], unique=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_diagnosis_id', sa.Integer(), nullable=True))
        batch_op.alter_column('patient_dob',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('patient_dob_est',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('patient_gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key('fk_patient_diagnosis', 'patient_diagnosis', ['patient_diagnosis_id'], ['id'])

    op.execute("INSERT INTO patient_diagnosis VALUES (1, 'Q21', '0', 'Ventricular septal defect', 'VSD')")
    op.execute("INSERT INTO patient_diagnosis VALUES (2, 'Q21', '1', 'Atrial septal defect', 'ASD')")
    op.execute("INSERT INTO patient_diagnosis VALUES (3, 'Q21', '2', 'Atrioventricular septal defect', 'AVSD')")
    op.execute("INSERT INTO patient_diagnosis VALUES (4, 'Q21', '3', 'Tetralogy of Fallot', 'TOF')")
    op.execute("INSERT INTO patient_diagnosis VALUES (5, 'Q21', '4', 'Aortopulmonary septal defect', 'APSD')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('patient_gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('patient_dob_est',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('patient_dob',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('patient_diagnosis_id')

    with op.batch_alter_table('patient_diagnosis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_diagnosis_name'))
        batch_op.drop_index(batch_op.f('ix_patient_diagnosis_icd_subcode'))
        batch_op.drop_index(batch_op.f('ix_patient_diagnosis_icd_code'))
        batch_op.drop_index(batch_op.f('ix_patient_diagnosis_dx_abbrev'))

    op.drop_table('patient_diagnosis')
    # ### end Alembic commands ###
