"""Facility chooser on provider form

Revision ID: 9a80efbe6ba9
Revises: 45a31f5c1409
Create Date: 2020-06-11 12:47:36.625007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a80efbe6ba9'
down_revision = '45a31f5c1409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('provider_facility_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'provider', 'facility', ['provider_facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_column('provider', 'provider_facility_id')
    # ### end Alembic commands ###
