"""empty message

Revision ID: c3bf2b366728
Revises: 
Create Date: 2020-06-04 12:07:26.916551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bf2b366728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_name', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_status_code_name'), 'patient_status', ['code_name'], unique=False)
    op.create_index(op.f('ix_patient_status_name'), 'patient_status', ['name'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('patient_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_status_id'], ['patient_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_first_name'), 'patient', ['first_name'], unique=False)
    op.create_index(op.f('ix_patient_last_name'), 'patient', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_last_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_first_name'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_patient_status_name'), table_name='patient_status')
    op.drop_index(op.f('ix_patient_status_code_name'), table_name='patient_status')
    op.drop_table('patient_status')
    # ### end Alembic commands ###
