openapi: 3.0.0
info:
  contact:
    email: orobinson@haiticardiac.org
    name: Owen Robinson
    url: 'https://www.haiticardiac.org/'
  title: Patient API
  version: '1.0'
servers:
  - url: 'http://localhost:5000/v1'
paths:
  '/diagnosis':
    get:
      tags:
        - Patient
      summary: Get all diagnoses.
      description: Get all diagnosis records.
      operationId: hca.patients.patient_api.get_diagnosis
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Diagnosis'
    post:
      tags:
        - Patient
      summary: Create a diagnosis
      description: Create a single diagnosis record.
      operationId: hca.patients.patient_api.post_diagnosis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiagnosisBase'
      responses:
        '201':
          description: Return the created diagnosis record.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diagnosis'
  '/patients':
    get:
      tags:
        - Patient
      summary: Get all Patients
      description: Get all Patient records.
      operationId: hca.patients.patient_api.get_patients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
    post:
      tags:
        - Patient
      summary: Create a Patient
      description: Create a single patient record.
      operationId: hca.patients.patient_api.post_patients
      requestBody:
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientBase'
      responses:
        '201':
          description: Return the inserted Patient record.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
  '/patients/{patient_uuid}':
    get:
      tags:
        - Patient
      summary: Get single Patient
      description: Get a single patient record.
      operationId: hca.patients.patient_api.get_patient_uuid
      parameters:
        - description: Patient unique identifier
          explode: false
          in: path
          name: patient_uuid
          required: true
          schema:
            type: string
          style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '404':
          description: Not Found
  '/patients/{patient_uuid}/diagnosis/{diagnosis_id}':
    post:
      tags:
        - Patient
      summary: Assign a Diagnosis to a Patient
      description: Assign a single Diagnosis record to a single Patient record.
      operationId: hca.patients.patient_api.post_patient_diagnosis
      parameters:
        - description: Patient unique identifier
          explode: false
          in: path
          name: patient_uuid
          required: true
          schema:
            type: string
          style: simple
        - description: Diagnosis identifier
          explode: false
          in: path
          name: diagnosis_id
          required: true
          schema:
            type: integer
          style: simple
      requestBody:
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientDiagnosisBase'
      responses:
        '201':
          description: Return the set of PatientDiagnosis records, including the newly inserted PatientDiagnosis.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PatientDiagnosis'
  '/providers':
    get:
      tags:
        - Provider
      summary: Get all Providers
      description: Get all Provider records.
      operationId: hca.providers.provider_api.get_providers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
    post:
      tags:
        - Provider
      summary: Create a Provider
      description: Create a single provider record.
      operationId: hca.providers.provider_api.post_providers
      requestBody:
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProviderBase'
      responses:
        '201':
          description: Return the inserted Provider record.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'
  '/providers/{provider_uuid}':
    get:
      tags:
        - Provider
      summary: Get single Provider
      description: Get a single provider record.
      operationId: hca.providers.provider_api.get_provider_uuid
      parameters:
        - description: Provider unique identifier
          explode: false
          in: path
          name: provider_uuid
          required: true
          schema:
            type: string
          style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'
        '404':
          description: Not Found
components:
  schemas:
    ProviderBase:
      x-tags:
        - Provider
      title: Provider (Create)
      description: Base Provider schema for new record creation via POST.
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        provider_type:
          description: 'Professional category of provider'
          type: string
        is_active:
          type: boolean
        notes:
          description: 'Free-text notes for provider'
          type: string
    Provider:
      x-tags:
        - Provider
      title: Provider
      description: ''
      allOf:
        - $ref: '#/components/schemas/ProviderBase'
        - type: object
          properties:
            id:
              type: integer
            uuid:
              type: string
