openapi: 3.0.0
info:
  contact:
    email: orobinson@haiticardiac.org
    name: Owen Robinson
    url: 'https://www.haiticardiac.org/'
  title: Patient API
  version: '1.0'
servers:
  - url: 'http://localhost:5000/v1'
paths:
  '/patients':
    get:
      tags:
        - Patient
      summary: Get all Patients
      description: Get all Patient records.
      operationId: hca.patients.patient_api.get_patients
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
          description: OK
    post:
      tags:
        - Patient
      summary: Create a Patient
      description: Create a single patient record.
      operationId: hca.patients.patient_api.post_patients
      requestBody:
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasePatient'
      responses:
        '201':
          description: Return the inserted Patient record.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
  '/patients/{uuid}':
    get:
      tags:
        - Patient
      summary: Get single Patient
      description: Get a single patient record.
      operationId: hca.patients.patient_api.get_patient_id
      parameters:
        - description: Patient unique identifier
          explode: false
          in: path
          name: uuid
          required: true
          schema:
            type: string
          style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: OK
        '404':
          description: Not Found
components:
  schemas:
    BasePatient:
      x-tags:
        - Patient
      title: 'Patient (Base)'
      description: 'Base Patient schema for POST requests'
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        date_of_birth:
          description: 'Date of birth in UTC YYYY-MM-DD'
          example: '2008-05-24'
          format: date
          type: string
        is_date_of_birth_estimate:
          type: boolean
        date_of_death:
          description: 'If patient is deceased, date of death in UTC YYYY-MM-DD'
          example: '2020-01-30'
          format: date
          type: string
        sex:
          type: string
    Patient:
      x-tags:
        - Patient
      title: Patient
      description: ''
      allOf:
        - $ref: '#/components/schemas/BasePatient'
        - type: object
          properties:
            id:
              type: integer
            uuid:
              type: string
            friendly_id:
              type: string
            diagnosis:
              type: array
              items:
                $ref: '#/components/schemas/PatientDiagnosis'
            clinical_details:
              $ref: '#/components/schemas/PatientClinicalDetails'
    PatientDiagnosis:
      x-tags:
        - Patient
      title: PatientDiagnosis
      description: ''
      type: object
      properties:
        is_primary:
          type: boolean
        is_suspected:
          type: boolean
        notes:
          type: string
        diagnosis:
          $ref: '#/components/schemas/Diagnosis'
    Diagnosis:
      x-tags:
        - Patient
      title: Diagnosis
      description: ''
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
        diagnosis:
          type: string
    PatientClinicalDetails:
      x-tags:
        - Patient
      title: Patient Clinical Details
      description: ''
      type: object
      properties:
        status:
          type: integer
        urgency:
          type: integer
        syndrome:
          type: integer
        syndrome_notes:
          type: string
        



